export {default as About} from './About'
export {default as Contact} from './Contact'
export {default as Services} from './Services'
export {default as Testimonial} from './Testimonial'
export {default as Home} from './Home'
